#!/usr/bin/env bash
# apply-profile.sh <manifest.json> [--force] [--no-activate]
# Renders one Codex profile overlay without editing the user's base config.toml.
set -euo pipefail

CORE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
MANIFEST="${1:-./manifest.json}"
FORCE=0
ACTIVATE=1
for arg in "$@"; do
  [ "$arg" = "--force" ] && FORCE=1
  [ "$arg" = "--no-activate" ] && ACTIVATE=0
done

[ -f "$MANIFEST" ] || { echo "codex apply: no manifest at $MANIFEST" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "codex apply: jq required" >&2; exit 1; }
PYTHON="$(command -v python3 2>/dev/null || command -v python 2>/dev/null || true)"
[ -n "$PYTHON" ] || { echo "codex apply: Python 3 required" >&2; exit 1; }
mkdir -p "$CODEX_DIR"

VIEW="$(mktemp "$CODEX_DIR/.harness-view.XXXXXX")"
RENDERED="$(mktemp "$CODEX_DIR/.harness-profile.XXXXXX")"
cleanup() { rm -f "$VIEW" "$RENDERED"; }
trap cleanup EXIT

bash "$CORE_DIR/lib/manifest-provider-view.sh" "$MANIFEST" codex > "$VIEW"
NAME="$(jq -r '.name // empty' "$VIEW" | tr -d '\r')"
case "$NAME" in
  ""|*[!A-Za-z0-9._-]*) echo "codex apply: invalid profile name '$NAME'" >&2; exit 1 ;;
esac

"$PYTHON" "$CORE_DIR/adapters/codex/render-profile.py" \
  "$VIEW" "$CORE_DIR/adapters/codex/mcp-catalog.json" > "$RENDERED"

TARGET="$CODEX_DIR/$NAME.config.toml"
MARKER='# Generated by tack. DO NOT EDIT.'
if [ -f "$TARGET" ] && ! grep -qxF "$MARKER" "$TARGET"; then
  if [ "$FORCE" -ne 1 ]; then
    echo "codex apply: $TARGET is not harness-managed; refusing to replace it." >&2
    echo "  Re-run with --force to back it up and continue." >&2
    exit 1
  fi
  TS="$(date +%Y%m%d_%H%M%S 2>/dev/null || echo now)"
  cp "$TARGET" "$TARGET.backup.$TS"
  echo "  backed up existing profile: $TARGET.backup.$TS"
fi

if cmp -s "$RENDERED" "$TARGET"; then
  echo "  Codex profile unchanged: $TARGET"
else
  mv "$RENDERED" "$TARGET"
  RENDERED=""
  echo "  Codex profile rendered: $TARGET"
fi
if [ "$ACTIVATE" -eq 1 ]; then
  echo "$NAME" > "$CODEX_DIR/.harness-active"
else
  echo "  Codex default profile unchanged (--no-activate)"
fi
bash "$CORE_DIR/adapters/codex/sync-runtime-files.sh" "$MANIFEST" "$VIEW" \
  || { echo "codex apply: runtime file sync failed" >&2; exit 1; }
bash "$CORE_DIR/adapters/codex/setup-plugin.sh" \
  || { echo "codex apply: harness plugin setup failed" >&2; exit 1; }
bash "$CORE_DIR/adapters/codex/setup-memory.sh" "$VIEW" \
  || { echo "codex apply: memory setup failed" >&2; exit 1; }
echo "==> Codex profile '$NAME' applied."
bash "$CORE_DIR/adapters/codex/verify-setup.sh" "$NAME" \
  || { echo "codex apply: verification failed" >&2; exit 1; }
