#!/usr/bin/env python3
"""Render one normalized Codex manifest view as a profile TOML document."""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path


MARKER = "# Generated by tack. DO NOT EDIT."
PERMISSION_KEYS = {"approval_policy", "sandbox_mode"}
RESERVED_CONFIG_KEYS = {"mcp_servers", "plugins"}
HARNESS_PLUGIN = "harness-policy@agent-harness"
DEFAULT_STATUS_LINE = [
    "model-with-reasoning",
    "current-dir",
    "git-branch",
    "context-remaining",
    "five-hour-limit",
    "weekly-limit",
]


def fail(message: str) -> None:
    raise ValueError(message)


def toml_key(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float) and math.isfinite(value):
        return repr(value)
    if isinstance(value, list):
        if any(isinstance(item, (dict, list)) or item is None for item in value):
            fail("TOML arrays may contain only scalar values")
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    fail(f"unsupported TOML value type: {type(value).__name__}")


def emit_table(data: dict[str, object], path: tuple[str, ...], lines: list[str]) -> None:
    scalars = {key: value for key, value in data.items() if not isinstance(value, dict)}
    children = {key: value for key, value in data.items() if isinstance(value, dict)}

    if path:
        lines.append("[" + ".".join(toml_key(part) for part in path) + "]")
    for key in sorted(scalars):
        value = scalars[key]
        if value is None:
            fail(f"null is not valid for config key {'.'.join(path + (key,))}")
        lines.append(f"{toml_key(key)} = {toml_value(value)}")
    if path and (scalars or children):
        lines.append("")

    for key in sorted(children):
        child = children[key]
        if not isinstance(child, dict):
            fail("internal renderer error")
        emit_table(child, path + (key,), lines)


def require_object(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        fail(f"{label} must be an object")
    return value


def build_config(view: dict[str, object], catalog: dict[str, object]) -> dict[str, object]:
    raw_config = require_object(view.get("config", {}), "providers.codex.config")
    config = json.loads(json.dumps(raw_config))
    reserved = sorted(RESERVED_CONFIG_KEYS.intersection(config))
    if reserved:
        fail(f"providers.codex.config cannot own reserved keys: {', '.join(reserved)}")

    permissions = require_object(view.get("permissions", {}), "providers.codex.permissions")
    unknown_permissions = sorted(set(permissions) - PERMISSION_KEYS)
    if unknown_permissions:
        fail(f"unknown Codex permission key(s): {', '.join(unknown_permissions)}")
    config.update(permissions)

    tui = require_object(config.setdefault("tui", {}), "providers.codex.config.tui")
    tui.setdefault("status_line", list(DEFAULT_STATUS_LINE))
    tui.setdefault("status_line_use_colors", True)

    features = require_object(config.setdefault("features", {}), "providers.codex.config.features")
    features["hooks"] = True
    memory = require_object(view.get("memory", {}), "memory")
    legacy = view.get("schema_version", 1) == 1
    memory_enabled = bool(memory.get("enabled", legacy))
    memory_engine = memory.get("engine", "claude-mem" if legacy else "none")
    features["memories"] = bool(memory_enabled and memory_engine == "native")

    plugins = require_object(view.get("plugins", {}), "providers.codex.plugins")
    rendered_plugins: dict[str, object] = {}
    for name, enabled in plugins.items():
        if not isinstance(enabled, bool):
            fail(f"Codex plugin {name} enabled state must be boolean")
        rendered_plugins[name] = {"enabled": enabled}
    if memory_engine == "claude-mem":
        rendered_plugins["claude-mem@claude-mem-local"] = {"enabled": memory_enabled}
    rendered_plugins[HARNESS_PLUGIN] = {"enabled": True}
    if rendered_plugins:
        config["plugins"] = rendered_plugins

    selected_mcp = view.get("mcp", [])
    if not isinstance(selected_mcp, list) or any(not isinstance(name, str) for name in selected_mcp):
        fail("mcp must be an array of strings")
    rendered_mcp: dict[str, object] = {}
    for name in selected_mcp:
        definition = catalog.get(name)
        if definition is None:
            fail(f"Codex MCP catalog has no entry for '{name}'")
        rendered_mcp[name] = require_object(definition, f"MCP catalog entry {name}")
    if rendered_mcp:
        config["mcp_servers"] = rendered_mcp

    return config


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: render-profile.py <provider-view.json> <mcp-catalog.json>", file=sys.stderr)
        return 2
    try:
        view = require_object(json.loads(Path(sys.argv[1]).read_text()), "manifest")
        catalog = require_object(json.loads(Path(sys.argv[2]).read_text()), "MCP catalog")
        config = build_config(view, catalog)
        lines = [MARKER, "# Applied profile: " + str(view.get("name", "unknown")), ""]
        emit_table(config, (), lines)
        print("\n".join(lines).rstrip() + "\n")
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"render-profile: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
