#!/usr/bin/env bash
# Verify harness-owned Codex profile state. No network calls.
set -uo pipefail

CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
PROFILE="${1:-$(cat "$CODEX_DIR/.harness-active" 2>/dev/null | tr -d '\r' || true)}"
errors=0
ok()   { echo "  ok: $1"; }
fail() { echo "  FAIL: $1"; echo "        Fix: $2"; errors=$((errors + 1)); }
warn() { echo "  WARN: $1"; echo "        Next: $2"; }

case "$PROFILE" in
  ""|*[!A-Za-z0-9._-]*) fail "invalid or missing Codex active profile '$PROFILE'" "run: tack use <name>" ;;
esac

CONFIG="$CODEX_DIR/$PROFILE.config.toml"
if [ -f "$CONFIG" ] && grep -qxF '# Generated by tack. DO NOT EDIT.' "$CONFIG"; then
  ok "Codex profile config: $PROFILE"
else
  fail "Codex profile config missing or unmanaged: $CONFIG" "run: tack use $PROFILE"
fi

if [ -f "$CODEX_DIR/AGENTS.md" ] \
  && grep -qF '<!-- >>> codex-harness policy >>>' "$CODEX_DIR/AGENTS.md" \
  && grep -qF '<!-- <<< codex-harness policy <<< -->' "$CODEX_DIR/AGENTS.md"; then
  ok "Codex AGENTS.md policy installed"
else
  fail "Codex AGENTS.md policy missing" "run: tack use $PROFILE"
fi

managed="$CODEX_DIR/.harness-managed-skills"
if [ -s "$managed" ]; then
  missing=""
  while IFS= read -r skill; do
    [ -f "$CODEX_DIR/skills/$skill/SKILL.md" ] || missing="$missing $skill"
  done < "$managed"
  [ -z "$missing" ] && ok "Codex managed skills present" \
    || fail "Codex managed skill files missing:$missing" "run: tack use $PROFILE"
else
  fail "Codex managed skill inventory missing" "run: tack use $PROFILE"
fi

if [ -f "$CONFIG" ] && grep -qE '^"memories" = (true|false)$' "$CONFIG"; then
  ok "Codex native memory policy explicit"
else
  fail "Codex native memory policy not explicit" "run: tack use $PROFILE"
fi

if [ -f "$CONFIG" ] && grep -qE '^"status_line" = \[' "$CONFIG"; then
  ok "Codex native status line configured"
else
  fail "Codex native status line missing" "run: tack use $PROFILE"
fi

plugin_status="$(cat "$CODEX_DIR/.harness-plugin-status" 2>/dev/null | tr -d '\r' || true)"
case "$plugin_status" in
  registered:*) ok "Codex policy plugin registered" ;;
  skipped) warn "Codex policy plugin setup skipped" "run tack use $PROFILE without HARNESS_NO_PLUGIN_SETUP" ;;
  *) warn "Codex policy plugin not registered" "run tack use $PROFILE, then review hooks with /hooks" ;;
esac

[ "$errors" -eq 0 ]
